services:
  directus:
    image: directus/directus:11.1.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - ./../.env.development
    environment:
      WEBSOCKETS_ENABLED: true
